:website:
  :id: "http://salimane.com"
  :title: "Salimane Adjao Moustapha"
  :description: "Building Stuff, Having Fun, Craving Profit"
  :hostname: "salimane.com"
  :domain: "salimane.com"
  :root_url: "http://salimane.com"