mode: development
media_root: media
media_url: /media
deploy_root: /home/salimane/htdocs/salimane.github.com
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.git.GitDatesPlugin
  - hyde.ext.plugins.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.sorter.SorterPlugin
  - hyde.ext.plugins.tagger.TaggerPlugin
  - hyde.ext.plugins.grouper.GrouperPlugin
  - hyde.ext.plugins.tagger.TaggerPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - hyde.ext.plugins.urls.UrlCleanerPlugin
  - extensions.images.ImageThumbnailsPlugin
  - hyde.ext.plugins.images.ImageSizerPlugin
  - hyde.ext.plugins.optipng.OptiPNGPlugin
  - hyde.ext.plugins.jpegoptim.JPEGOptimPlugin
  - hyde.ext.plugins.uglify.UglifyPlugin
  - extensions.cdn.CdnPlugin
context:
  data:
    base: http://salimane.com
    languages:
      en: English

meta:
  nodemeta: meta.yaml
  author: Salimane Adjao Moustapha
  title: "Do you get things done ?"
  created: git
  modified: git
  language: en
  analytics: UA-28010526-1
  keywords: "salimane adjao moustapha"

typekit: hen2cfo
less:
  app: lessc
  args:
    compress: ""
optipng:
  app: /usr/bin/optipng
  args:
    quiet: ""
jpegoptim:
  app: /usr/bin/jpegoptim
  args:
    max: "70"
    strip-all: ""
uglify:
  app: /usr/bin/uglifyjs
  args:
    no-copyright: ""
urlcleaner:
  index_file_names:
    - index.html
  append_slash: true
markdown:
  extensions:
    - codehilite
    - extra
    - toc
    - mathjax
  output_format: html
sorter:
  name:
    attr:
      - relative_path
  time:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
  time_en:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: en
tagger:
  sorter: time
